# Grunt aliases
---
# Build everything
build:
  - 'build:css'
# Build CSS
'build:css':
  - 'copy'
  - 'sass:build'
  - 'postcss:build'

# Check health of the project
check:
  - 'eslint'
# Default task
default:
  - check
