# Grunt aliases
---
# Build everything
build:
  - 'build:js'
  - 'build:ccs'
# Build JavaScript from assets to production
'build:js':
  - 'uglify'
# Build CSS
'build:css':
  - 'cssmin'
# Check health of the project
check:
  - 'jshint'
  - 'jsonlint'
  - 'jsvalidate'
# Default task
default:
  - check
  - build
