# Grunt aliases
---
# Build everything
build:
  - 'build:css'
  - 'build:jst'
  - 'build:js'
# Precompile JavaScript templates
'build:jst':
  - 'lodash:templates'
# Build JavaScript from assets to production
'build:js':
  - 'browserify'
  - 'uglify'
# Build CSS
'build:css':
  - 'copy'
  - 'sass:build'
  - 'postcss:build'
# Check health of the project
check:
  - 'jshint'
  - 'jsonlint'
  - 'jsvalidate'
  - 'jscs'
# Default task
default:
  - check
  - build
