language: node_js
node_js:
- node

sudo: false

cache:
  yarn: true
  directories:
  - node_modules

install:
- yarn global add grunt-cli
- yarn --ignore-optional

script:
- grunt check
- yarn test --coverage --runInBand

after_success:
- yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info

notifications:
  slack:
    secure: W3StABr+AdcdQawTObK4nbsnn5nLrTTtZfVpD/GEN6gvSOQcykbGEC5+ceYg0jn5b4StDyCiTo5blEsrpVICFpYKc44+ogah+qaGRUfVRS/rpOvn4AueXTWn4JxhZzuxqKMiTmyW+MQG0uYM7sk7Q5S+15jj6ilkj4QATaBVNbY=

deploy:
  provider: npm
  email: webmaster@yoast.com
  api_key:
    secure: "YNdccmeIVtCxMRmJ7cJfaSCfmYHgnwLiauKwkvTV8KB0fW3dU/AiG8ijsQ9fzGu3QXt5+TajzZ+E9kLg1u1vEpK4UGQap/L4p+MVDf91o1UVNOj4VcMXAojYHKLTAdLf13izalqg/tH6nB54YoQ0CfiorQdIjp6n0QXn45A8X+m9p3bZuSHpfZ61UNdRYV20LkRSUVhiPL2TR/s0dvFXQYwo9gqAJs9UGcygLJvbA9wOxb6SEzU2PnpGp9pFmFeyhqOSloygL+Nr4iqVHNp+FQHe07xmFBn0F+3PgQH1KAmJrHoJIScLM+dgf+6MtnH30lK/s7AgI3v/qafxeEJjs2+eXyTUfJS0AwIXho7G4GD2dN5dDEM6hQtSqAPzikRdazSBssYdzW6S7804zKn42uzIDzj2b+aW42nWkUbt+fSP/CqmNJKeA3QFoRPA9fUaKDNCTIBYg9lN9vxEDktcDSJOe3HaXagn1I4cpN1EgPmpLgZjhqt7K00r7glQqJb4n0oq4T7OUa7eFYDXvi6Fj4HXLOn11MIG0X6aX9gnQAJODBNAK7wMdSXdK0a9j8fyv7iD42rR2rgBafl9vu4Du9XcyTt8SqaeOvYIiDhlt8J0YD3OxvrT7eoUaGEdspCAL5xUO/4p4pems8YCNtQKTVk34snGAkozilRUegGWj1k="
  on:
    tags: true
    repo: Yoast/yoast-components
