language: node_js
node_js:
- node

sudo: false

cache:
  yarn: true
  directories:
  - node_modules

install:
- yarn global add grunt-cli
- yarn --ignore-optional

script:
- grunt check
- yarn test -- --coverage --runInBand

after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info

notifications:
  slack:
    secure: W3StABr+AdcdQawTObK4nbsnn5nLrTTtZfVpD/GEN6gvSOQcykbGEC5+ceYg0jn5b4StDyCiTo5blEsrpVICFpYKc44+ogah+qaGRUfVRS/rpOvn4AueXTWn4JxhZzuxqKMiTmyW+MQG0uYM7sk7Q5S+15jj6ilkj4QATaBVNbY=

deploy:
  provider: npm
  email: webmaster@yoast.com
  api_key:
    secure: "CGjq/PO0mub/h4XP4V4dijnSZHUw5u5ihfXdMrF3IcgMM+94Mm7L8C2mAsGGIsIh1sdYno82aL0933ctop3RUAHhyMXtLk5wVvqtCcX0yhhoozlFKEov30f7OTFTrcz3D9yZNHTMquz1roWTy0gt2QTuA/fz4SERKcVU4RKrClMcN/5+rL4IhiFRN7/AA2Ze0y6nLYN5+J9oMGV7SNKzZAHvjD/+AvNf1l5uX0tjTkg2JJiw2AXIz2Sxlgy0eGwHQW755lWEvMPcCF9b5iE7X0Y6JtvUAx155GCMiluPrdKklFGAiRjQPl4vLwkUuA1W14ljcKSnZFS5jcrhTiV+2lExC7h0FMnj+IgfpoNXsIkaXO0ittT/Ie2VVp0n4sfYaleebpMoIwXVUaSNKLztx7pmGvudsw2YTLaldbQjaVxKM6mqRcFd2WSUZ207V4T70ac5WSv1co4B4hjT2GrJ/Yspv6srubM73MWlPwgXBIpP/Zl3ag58d+8z/zinYctVlmzle56goHyR3sd3mtFtWq17WAHK7Xqs0pB07XFpINfF8sdFVPDfsWByryrt2s60aA2dWtVlqAW8MYEQzLIOYzpSgOcnbAp9EvqJ6uZx4RyYyxWdIfzBCh9o5uQqw97s7zyQVHLhKmNBUqVNR7+oryHn+X9ZRIRC1cJvjrS2ipY="
  on:
    tags: true
    repo: Yoast/yoast-components
