# Grunt aliases
---
# Build everything
build:
  - 'build:css'
# Build CSS
'build:css':
  - 'sass:build'
  - 'postcss:build'

# Check health of the project
check:
  - 'eslint'

publish:
  - 'copy:publish'

# Default task
default:
- check
