name: yoast-e2e-tests
on:
  push:
    branches: [ try/e2e-tests-package ]

jobs:
  yoast-e2e-tests-wp-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3.24'

    - name: Install Dependencies
      run: composer update
