name: yoast-e2e-tests
on:
  workflow_dispatch:
  push:
    branches: [ try/e2e-tests-package ]

jobs:
  yoast-e2e-tests-wp-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3.24'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer packages
      run: composer install

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}


    - name: Run yarn command
      run: yarn

    - name: Build the plugin
      run: grunt build:dev

    run: cd packages/e2e-tests

    run: bash e2e-test-env-setup.sh