name: yoast-e2e-tests
on:
  workflow_dispatch:
  push:
    branches: [ try/e2e-tests-package ]

jobs:
  yoast-e2e-tests-wp-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3.24'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer packages
      run: composer install

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}


    - name: Run Node command
      run: |
        yarn install

    - name: Build the plugin
      run: grunt build:dev

    - name: Setup the environment and run the tests
      run: |
        yarn wp-env start
        yarn wp-env run tests-cli wp plugin install "https://github.com/Yoast/wordpress-seo/blob/try/e2e-tests-package/packages/e2e-tests/data/yoast-simple-custom-post-type.zip?raw=true"
        yarn wp-env run tests-cli wp plugin activate yoast-simple-custom-post-type
        cd packages/e2e-tests
        yarn test:e2e
