name: yoast-e2e-tests
on:
  workflow_dispatch:

jobs:
  yoast-e2e-tests-wp-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Node version
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install Composer dependencies
      uses: php-actions/composer@v4
      with:
        php_version: 7.4

    - name: Install wp-env
      run: |
        npm install @wordpress/env
        wp-env start
