name: yoast-e2e-tests
on:
  workflow_dispatch:
  push:
    branches: [ try/e2e-tests-package ]

jobs:
  yoast-e2e-tests-wp-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3.24'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer packages
      run: composer install

    - uses: c-hive/gha-yarn-cache@v1

    - name: Run Node command
      run: |
        yarn

    - name: Build the plugin
      run: grunt build:dev

    - name: Execute the e2e-test-env-setup.sh file
      run: |
        npm install @wordpress/env
        cd packages/e2e-tests
        bash e2e-test-env-setup.sh
