name: yoast-e2e-tests
on:
  push:
    branches:
      - try/yoast-e2e-tests-package
  workflow_dispatch:

jobs:
  yoast-e2e-tests-wp-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Set Node version
#      uses: actions/setup-node@v2
#      with:
#        node-version: '12'

    - name: Composer Install
      uses: php-actions/composer@v6
