name: yoast-e2e-tests
on:
  workflow_dispatch:
  push:
    branches: [ try/e2e-tests-package ]

jobs:
  yoast-e2e-tests-wp-latest:

    env:
      WP_VERSION: latest

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3.24'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer packages
      run: composer install

    - name: Run Node command
      run: |
        yarn

    - name: Build the plugin
      run: grunt build:dev

    - name: Setup the environment and run the tests
      run: |
        wp-env start
        cd packages/e2e-tests
        wp-env run tests-cli wp plugin install "https://github.com/Yoast/wordpress-seo/blob/try/e2e-tests-package/packages/e2e-tests/data/yoast-simple-custom-post-type.zip?raw=true"
		wp-env run tests-cli wp plugin activate yoast-simple-custom-post-type
        yarn test:e2e
